name: Deploy backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

jobs:
  deploy:
    name: Deploy backend to ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_ADDRESS }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build"
          target: "test"