name: Deploy backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy backend to ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 400 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_ADDRESS }} >> ~/.ssh/known_hosts

      - name: copy the directories
        run: |
          mkdir cvpdfviewer
          mv ./backend cvpdfviewer
          mv ./frontend cvpdfviewer
          scp -i ~/.ssh/ec2_key.pem \
            -r \
            $GITHUB_WORKSPACE/cvpdfviewer \
            ubuntu@${{ secrets.EC2_ADDRESS }}:/home/ubuntu/

      - name: compile the frontend and backend
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_ADDRESS }} "
          npm install   --prefix /home/ubuntu/cvpdfviewer/frontend && \
          npm install   --prefix /home/ubuntu/cvpdfviewer/backend && \

          npm run build --prefix /home/ubuntu/cvpdfviewer/frontend && \
          npm run build --prefix /home/ubuntu/cvpdfviewer/backend  && \

          /home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2 stop server
          /home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2 start \
          /home/ubuntu/cvpdfviewer/backend/build/server.js \
          -i max --name server
          "









