name: Deploy backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

jobs:
  deploy:
    name: Deploy backend to ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 400 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_ADDRESS }} >> ~/.ssh/known_hosts
      - name: copy the directories
        run: scp -i ~/.ssh/ec2_key.pem -r $GITHUB_WORKSPACE/* ubuntu@${{ secrets.EC2_ADDRESS }}:/home/ubuntu/cvpdfviewer
      - name: compile the frontend
        run: ssh -i ~/.ssh/ec2_key.pem "
            npm run build --prefix /home/ubuntu/cvpdfviewer/frontend
            && npm run build --prefix /home/ubuntu/cvpdfviewer/backend
            && npm run start --prefix /home/ubuntu/cvpdfviewer/backend
          "